export {
  clearTileAccessCache,
  getGrantedApplicationCodes,
  getRequestEmail,
  normalizeEmail,
  requireTileAccess,
  requireTileScope,
} from "./rbac"
export type { TileAccessResult } from "./rbac"
export { loadGrantedApplicationCodes, loadGrantedScopes } from "./rbac-store"
export { getUserDisplayName } from "./identity"
export { isModuleEnabled, moduleLicensingConfig } from "./module-licensing"
export type { ModuleLicensingConfig } from "./module-licensing"
export {
  GROUP_DESCRIPTION as OPENWEBUI_GROUP_DESCRIPTION,
  GROUP_NAME_PREFIX as OPENWEBUI_GROUP_NAME_PREFIX,
  OpenwebuiGroupAlreadyMappedError,
  attachRoleGroup,
  detachRoleGroup,
  emptyGroupMembership,
  getRoleGroupMapping as getOpenwebuiRoleGroupMapping,
  groupNameForRoleCode,
  listOpenwebuiGroups,
  openwebuiConfig,
  previewRoleGroupSync,
  reconcileAllMappedGroups,
  reconcileEverything,
  reconcileRoleGroup,
  reconcileRoleGroups,
} from "./openwebui-sync"
export type {
  AttachRoleGroupError,
  AttachRoleGroupInput,
  OpenwebuiFullSyncResult,
  OpenwebuiPlanEntry,
  OpenwebuiSyncResult,
  RoleGroupSyncPreview,
} from "./openwebui-sync"
export { OpenwebuiClientError } from "./openwebui-client"
export type { OpenwebuiClientFailure, OpenwebuiConfig, OpenwebuiGroupSummary } from "./openwebui-client"
export {
  ILUSTROMAT_APP_CODE,
  MANAGE_TEMPLATES_SCOPE,
  MissingTemplateAssetError,
  UnknownTemplateError,
  createFrameTemplate,
  deleteFrameTemplate,
  duplicateFrameTemplate,
  frameTemplateInputSchema,
  generateTemplateId,
  getFrameTemplate,
  getTemplateAsset,
  listFrameTemplates,
  listTemplateAssets,
  saveTemplateAsset,
  setFrameTemplateActive,
  updateFrameTemplate,
} from "./ilustromat"
export type { FrameTemplateInput, TemplateAssetInput } from "./ilustromat"
export {
  ADMIN_ROLE_CODE,
  SYSTEM_CONFIG_APP_CODE,
  ModuleNotLicensedError,
  NativeApplicationImmutableError,
  NativeCreationNotAllowedError,
  SelfLockoutError,
  SystemRoleProtectedError,
  UnknownApplicationError,
  UnknownApplicationScopeError,
  UnknownRoleError,
  UnknownUserError,
  activateApplication,
  activateApplicationInputSchema,
  applicationInputSchema,
  applicationPatchSchema,
  applicationScopePatchSchema,
  createApplication,
  createRole,
  createUser,
  deleteApplication,
  deleteRole,
  getInstanceAppearance,
  instanceAppearanceInputSchema,
  listApplicationRoleIds,
  listApplicationScopeGrants,
  listApplicationScopes,
  listApplications,
  listHubApplications,
  listUnactivatedNativeApplications,
  listRoles,
  listUsers,
  renameApplicationScope,
  roleInputSchema,
  rolePatchSchema,
  setApplicationRoles,
  setApplicationScopeRoles,
  setInstanceAppearance,
  setRoleApplications,
  setUserRoles,
  updateApplication,
  updateRole,
  updateUser,
  userInputSchema,
  userPatchSchema,
} from "./system-config"
export type {
  ActivateApplicationInput,
  ApplicationInput,
  ApplicationPatch,
  ApplicationScopeGrant,
  ApplicationScopePatch,
  ApplicationScopeSummary,
  InstanceAppearance,
  InstanceAppearanceInput,
  RoleInput,
  RolePatch,
  RoleSummary,
  UserInput,
  UserPatch,
  UserWithRoles,
} from "./system-config"
export {
  VISUAL_GURU_APP_CODE,
  createGeneration,
  deleteGeneration,
  getMyGeneration,
  listMyGenerations,
  listMyGenerationsWithFirstVariant,
} from "./visual-guru"
export type {
  CreateGenerationInput,
  GenerationListItem,
  GenerationVariantInput,
  GenerationWithVariants,
} from "./visual-guru"
export {
  DOCUMENT_PARSER_APP_CODE,
  createQueuedJob,
  getMyJob,
  listMyJobs,
  markJobDone,
  markJobError,
  markJobProcessing,
} from "./document-parser"
export type {
  CreateQueuedJobInput,
  MarkJobDoneInput,
  MarkJobErrorInput,
} from "./document-parser"
export {
  GEO_SCORE_CALCULATOR_APP_CODE,
  GEO_SCORE_CONFIG_DEFAULTS,
  GeoScoreConfigMissingError,
  deleteMyCalculation,
  getGeoScoreConfig,
  getMyCalculation,
  listMyCalculations,
  resetGeoScoreConfig,
  saveGeoScoreCalculation,
  updateGeoScoreConfig,
} from "./geo-score-calculator"
export type { SaveCalculationInput, UpdateGeoScoreConfigInput } from "./geo-score-calculator"
export {
  addForbiddenPhrase,
  clientProfileInputSchema,
  createClientProfile,
  createGenerationJob,
  createMarketProfile,
  createTemplate,
  deleteMyClientProfile,
  deleteMyMarketProfile,
  deleteTemplate,
  duplicateTemplate,
  finishGenerationJob,
  GENERATION_JOB_ITEM_STATUSES,
  getMyArchiveEntry,
  getMyClientProfile,
  getMyGenerationJob,
  getMyMarketProfile,
  getTemplate,
  listMyArchive,
  listMyClientProfiles,
  listMyForbiddenPhrases,
  listMyMarketProfiles,
  listTemplates,
  markGenerationJobRunning,
  marketProfileInputSchema,
  removeForbiddenPhrase,
  saveArchiveEntry,
  templateInputSchema,
  updateGenerationJobItem,
  updateMyClientProfile,
  updateMyMarketProfile,
  updateTemplate,
} from "./content-guru"
export type {
  AddForbiddenPhraseInput,
  ClientProfileInput,
  CreateGenerationJobItemInput,
  GenerationJobItem,
  GenerationJobItemStatus,
  MarketProfileInput,
  SaveArchiveEntryInput,
  TemplateInput,
} from "./content-guru"
